import os
import matplotlib.pyplot as plt
import seaborn as sns
from fpdf import FPDF
from backend.app.engines.data_engine import data_engine
import google.generativeai as genai
from dotenv import load_dotenv
import pandas as pd

load_dotenv()

REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

class PDFReport(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, 'AutoAnalyst Pro - Enterprise Report', 0, 0, 'R')
            self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def title_page(self, title, subtitle):
        self.add_page()
        self.set_fill_color(240, 244, 248) # Light Blue/Gray Background
        self.rect(0, 0, 210, 297, 'F')
        
        self.set_y(80)
        self.set_font('Arial', 'B', 36)
        self.set_text_color(30, 41, 59) # Dark Slate
        self.cell(0, 20, title, 0, 1, 'C')
        
        self.set_font('Arial', '', 16)
        self.set_text_color(100, 116, 139) # Slate
        self.cell(0, 10, subtitle, 0, 1, 'C')
        
        self.ln(50)
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, "Generated by AutoAnalyst AI", 0, 1, 'C')

    def add_kpi_grid(self, kpis):
        self.set_y(self.get_y() + 10)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(30, 41, 59)
        self.cell(0, 10, "Key Performance Indicators", 0, 1, 'L')
        self.ln(5)

        # Draw 3 KPI Boxes
        col_width = 60
        start_x = 15
        y = self.get_y()
        
        for i, (label, value) in enumerate(kpis.items()):
            if i > 2: break # Max 3 KPIs for row 1
            x = start_x + (i * (col_width + 5))
            
            # Box
            self.set_fill_color(255, 255, 255)
            self.set_draw_color(226, 232, 240)
            self.rect(x, y, col_width, 30, 'DF')
            
            # Label
            self.set_xy(x, y + 5)
            self.set_font('Arial', '', 10)
            self.set_text_color(100, 116, 139)
            self.cell(col_width, 5, label, 0, 2, 'C')
            
            # Value
            self.set_font('Arial', 'B', 14)
            self.set_text_color(37, 99, 235) # Blue
            self.cell(col_width, 10, str(value), 0, 0, 'C')
            
        self.ln(35)

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(30, 41, 59)
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_draw_color(37, 99, 235)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.set_text_color(51, 65, 85)
        self.multi_cell(0, 7, body)
        self.ln()

class ReportEngine:
    def __init__(self):
        api_key = os.getenv("GOOGLE_API_KEY")
        if api_key:
            genai.configure(api_key=api_key)
            self.model = genai.GenerativeModel("models/gemini-2.5-flash")
        else:
            self.model = None

    def generate_charts(self, df, dataset_id):
        chart_paths = []
        sns.set_theme(style="white", palette="muted") # Cleaner theme
        
        # 1. Correlation (Top Insight)
        num_cols = df.select_dtypes(include=['number'])
        if len(num_cols.columns) > 1:
            plt.figure(figsize=(8, 6))
            corr = num_cols.corr()
            sns.heatmap(corr, annot=True, cmap='Blues', fmt=".2f", linewidths=.5, cbar=False)
            plt.title('Correlation Matrix (Darker = Stronger Relationship)', fontsize=12, pad=20)
            path = f"{REPORT_DIR}/{dataset_id}_corr.png"
            plt.savefig(path, bbox_inches='tight', dpi=150)
            plt.close()
            chart_paths.append({"title": "Strategic Drivers", "path": path})

        # 2. Distribution (Bar/Hist)
        for col in num_cols.columns[:2]: # Limit to top 2 important numeric
            plt.figure(figsize=(8, 4))
            sns.histplot(df[col].dropna(), kde=True, color="#3b82f6", edgecolor=None, alpha=0.6)
            plt.title(f'Distribution of {col}', fontsize=12)
            plt.xlabel(col, fontsize=10)
            plt.ylabel("Frequency", fontsize=10)
            sns.despine() # Remove ugly borders
            path = f"{REPORT_DIR}/{dataset_id}_{col}_dist.png"
            plt.savefig(path, bbox_inches='tight', dpi=150)
            plt.close()
            chart_paths.append({"title": f"Deep Dive: {col}", "path": path})
            
        return chart_paths

    def generate_report(self, dataset_id: str):
        try:
            df = data_engine.load_data(dataset_id)
            
            # --- CALCULATE KPIs ---
            kpis = {}
            if 'Profit' in df.columns:
                kpis['Total Profit'] = f"${df['Profit'].sum():,.0f}"
                kpis['Avg Profit'] = f"${df['Profit'].mean():,.0f}"
            elif len(df.select_dtypes(include='number').columns) > 0:
                 col = df.select_dtypes(include='number').columns[0]
                 kpis[f'Avg {col}'] = f"{df[col].mean():.1f}"
            kpis['Total Rows'] = str(len(df))

            # --- AI ANALYSIS ---
            summary = df.describe(include='all').to_string()
            prompt = f"""
            Act as a Strategy Consultant. Write a high-impact summary for this data:
            {summary}
            
            Sections required (Keep brief):
            1. **Executive Summary**: The main story.
            2. **Strategic Recommendations**: 3 bullet points.
            
            Tone: Professional, Direct. No markdown symbols like ** or ## in output.
            """
            analysis_text = "Analysis Unavailable."
            if self.model:
                res = self.model.generate_content(prompt)
                analysis_text = res.text.replace('**', '').replace('##', '') # Clean markdown

            # --- BUILD PDF ---
            pdf = PDFReport()
            
            # Page 1: Title & KPIs
            pdf.title_page("Data Intelligence Report", f"Dataset: {dataset_id[:8]}...")
            
            pdf.add_page()
            pdf.chapter_title("Executive Dashboard")
            pdf.add_kpi_grid(kpis) # The Big Numbers
            
            pdf.chapter_body(analysis_text) # The Text
            
            # Page 2+: Visuals
            charts = self.generate_charts(df, dataset_id)
            pdf.add_page()
            pdf.chapter_title("Visual Evidence")
            
            for chart in charts:
                if pdf.get_y() > 200: pdf.add_page() # Auto page break for charts
                pdf.set_font('Arial', 'B', 12)
                pdf.cell(0, 10, chart['title'], 0, 1)
                pdf.image(chart['path'], w=160)
                pdf.ln(10)

            output_path = f"{REPORT_DIR}/Report_{dataset_id}.pdf"
            pdf.output(output_path)
            
            return output_path

        except Exception as e:
            print(f"Report Error: {e}")
            return None

report_engine = ReportEngine()
